spring.application.name=bd_capacitaciones

spring.datasource.url=jdbc:mysql://localhost:3306/bd_capacitaciones
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

